"""Review pipeline stage sequencing."""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field

from app.services.llm_review_service import LLMReviewService
from app.services.report_service import ReportService
from app.services.repository_service import RepositoryService, RepositorySummary
from app.services.static_analysis_service import StaticAnalysisService

logger = logging.getLogger(__name__)


@dataclass
class PipelineContext:
    """Per-task state shared across pipeline steps."""

    repository_url: str
    branch: str
    repository_service: RepositoryService = field(init=False)
    repository_summary: RepositorySummary | None = None

    def __post_init__(self) -> None:
        self.repository_service = RepositoryService(self.repository_url, self.branch)

    def cleanup(self) -> None:
        self.repository_service.cleanup()


class ReviewPipeline:
    """
    Stateless stage runner.

    Shared services live on the pipeline; per-task data lives on PipelineContext.
    """

    def __init__(self, llm_review_service: LLMReviewService) -> None:
        self.static_analysis_service = StaticAnalysisService()
        self.llm_review_service = llm_review_service
        self.report_service = ReportService()

    async def run_step(self, step_id: str, context: PipelineContext) -> None:
        """
        Execute one pipeline stage.

        Args:
            step_id: Pipeline step identifier.
            context: Task-scoped state for this review.
        """

        repo = context.repository_service
        logger.info(
            "Running pipeline step '%s' for %s@%s",
            step_id,
            context.repository_url,
            context.branch,
        )

        if step_id == "clone":
            await asyncio.to_thread(repo.clone_repository)
            return

        if step_id == "scan":
            context.repository_summary = await asyncio.to_thread(repo.scan_repository)
            return

        if step_id == "static":
            # TODO: Use context.repository_service.local_path
            return

        if step_id == "chunk":
            # TODO: Chunk from local_path, store chunks on context
            return

        if step_id == "llm":
            # TODO: Review context.chunks
            return

        if step_id == "merge":
            # TODO: Merge findings into context
            return

        if step_id == "report":
            # Report body is generated by WorkerService after all steps.
            return

        logger.warning("Unknown pipeline step: %s", step_id)
