'use client'

import type { Review } from '@/types'

interface ReviewSummaryProps {
  review: Review
}

export function ReviewSummary({ review }: ReviewSummaryProps) {
  const metrics = [
    ['Overall', review.metrics.overallScore],
    ['Security', review.metrics.securityScore],
    ['Performance', review.metrics.performanceScore],
    ['Maintainability', review.metrics.maintainabilityScore],
    ['Code Quality', review.metrics.codeQualityScore],
    ['Architecture', review.metrics.architectureScore],
  ] as const

  return (
    <section className="space-y-4">
      <div className="rounded-lg border border-zinc-200 bg-white p-6">
        <h2 className="text-xl font-semibold">
          {review.repository.owner}/{review.repository.name}
        </h2>
        <p className="mt-1 text-sm text-zinc-500">{review.repositoryUrl}</p>
        <p className="mt-1 text-sm text-zinc-500">Branch: {review.branch}</p>
        <p className="mt-3 text-sm text-zinc-600">
          {review.repository.description || 'No description'}
        </p>
      </div>

      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        {metrics.map(([label, score]) => (
          <div key={label} className="rounded-lg border border-zinc-200 bg-white p-4">
            <p className="text-sm text-zinc-500">{label}</p>
            <p className="mt-1 text-2xl font-semibold">{score}</p>
          </div>
        ))}
      </div>

      <div className="rounded-lg border border-zinc-200 bg-white p-6">
        <h3 className="font-semibold">Statistics</h3>
        <ul className="mt-3 space-y-1 text-sm text-zinc-600">
          <li>Files: {review.repository.fileCount}</li>
          <li>Directories: {review.repository.dirCount}</li>
          <li>Total lines: {review.repository.totalLines}</li>
          <li>
            Issues by severity — critical: {review.issueSeverity.critical}, high:{' '}
            {review.issueSeverity.high}, medium: {review.issueSeverity.medium}, low:{' '}
            {review.issueSeverity.low}, info: {review.issueSeverity.info}
          </li>
        </ul>
      </div>

      <div className="rounded-lg border border-zinc-200 bg-white p-6">
        <h3 className="font-semibold">Recommendations</h3>
        <p className="mt-2 text-sm text-zinc-600">
          Replace this placeholder with recommendations generated by the report pipeline.
        </p>
      </div>
    </section>
  )
}
